name: Build, Scan, and Push image to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/n2q6y9g9

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.run_number }}
          docker build -t mediplus:${IMAGE_TAG} .




      - name: Tag and push image to Amazon ECR
        run: |
          IMAGE_TAG=${{ github.run_number }}
          docker tag mediplus:${IMAGE_TAG} public.ecr.aws/n2q6y9g9/mediplus:${IMAGE_TAG}
          docker push public.ecr.aws/n2q6y9g9/mediplus:${IMAGE_TAG}
