name: Build and Push image to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3



      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag and Push Docker image
        run: |
          IMAGE_URL=${{ secrets.REGISTRY_NAME }}/mediplus:${{ github.run_number }}
          docker build -t $IMAGE_URL -f ./Dockerfile .
          docker push $IMAGE_URL




      # - name: Tag and push image to Amazon ECR
      #   run: |
      #     IMAGE_TAG=${{ github.run_number }}
      #     docker tag mediplus:latest 030283508812.dkr.ecr.eu-north-1.amazonaws.com/mediplus:latest
      #     docker push 030283508812.dkr.ecr.eu-north-1.amazonaws.com/mediplus:latest
